Landing page cleanup
TheBuilderDAO/kafe pull request #126
Opened 2022-04-08 05:24 UTC by vunderkind

2022-04-08 20:01 UTC, Necmttn requested changes
cam you also compress dark mode bg images they are about 300 & 500 kb per file. compare 20-40 kb light mode ones. I believe we don't need to include the black background in the image itself, @ianbach  can you help us to export without bg?

2022-04-08 20:01 UTC, Necmttn commented on apps/web/components/Carousel/GuidesCarousel.tsx
> +    <div className="cursor-pointer">
can you add this to proposal cards as well

2022-04-08 20:09 UTC, ianbach commented on apps/web/components/Carousel/GuidesCarousel.tsx
> +    <div className="cursor-pointer">
Yes I can compress - unfortunately we do need the BG in them due to how I build the noise gradient in Figma :(

2022-04-08 20:11 UTC, Necmttn commented on apps/web/components/Carousel/GuidesCarousel.tsx
> +    <div className="cursor-pointer">
if I'm not wrong you could have the noise bg on transparent bg then we place it on black bg via CSS then we can have the same result on the app?

2022-04-08 20:13 UTC, ianbach commented on apps/web/components/Carousel/GuidesCarousel.tsx
> +    <div className="cursor-pointer">
![Learn_d](https://user-images.githubusercontent.com/3217930/162520753-b4ae619a-2ff3-4907-9013-7f2fc8f89c20.jpg)
![propose_d](https://user-images.githubusercontent.com/3217930/162520759-143c4751-ec7e-40ea-8dc6-3745eb88bc58.jpg)
![vote_d](https://user-images.githubusercontent.com/3217930/162520762-c10abd36-8edb-4804-b7c2-b6d981e542a4.jpg)

2022-04-08 20:28 UTC, ianbach commented on apps/web/components/Carousel/GuidesCarousel.tsx
> +    <div className="cursor-pointer">
> 

unfortunately not - it's to do with how I've achieved the grain effect. In future I can explore how to make this transparent but I think for now we just use jpgs

2022-04-09 05:51 UTC, Necmttn commented on apps/web/components/Carousel/GuidesCarousel.tsx
> +    <div className="cursor-pointer">
Ah gotcha understood 🙌
thank you.

2022-04-19 11:57 UTC, merged