Github Action Docs
TheBuilderDAO/kafe pull request #180
Opened 2022-04-27 11:09 UTC by Necmttn

# Guide Outline

> Provide a one or two paragraph outline of your guide. You should mention the overall topic, and what you expect learners to acheive when completing your guide.

## Link to Proposal

> Include a link to the related proposal on Kafé (e.g. <https://dev.builderdao.io/vote/my-proposal-slug>)

## Comments

> Please add any comments or information for the reviewers that will assist them in completing the review process. Link to any supporting documentation, especially references you have used in the process of writing your guide.

2022-04-27 23:15 UTC, pyr0gan requested changes

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_actions/check-required-reviewer.mdx
> +<Authors date="April 27th, 2022">
Is there a way for us to update the timestamp here automatically, or is this something that authors will need to do manually any time they edit a document?

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_actions/check-required-reviewer.mdx
> +<Authors date="April 27th, 2022">
Is there a way for us to update the timestamp here automatically, or is this something that authors will need to do manually any time they edit a document?

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_actions/check-required-reviewer.mdx
> +```
This gets me thinking: Should we run a linter on .mdx files? Or is that overkill?

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_actions/check-required-reviewer.mdx
> +```
This gets me thinking: Should we run a linter on .mdx files? Or is that overkill?

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/labeler.mdx
> +We are using [actions/labeler@v4](https://github.com/actions/labeler) from Github to identify the labels for the pull request. The labeler is a simple tool that allows you to label a pull request wit
> We are using [actions/labeler@v4](https://github.com/actions/labeler) from GitHub to identify and apply labels for the pull request. It is a simple tool that allows us to label a pull request based on the files it contains. For example, pull requests containing files in the `apps/docs` directory will be labelled as `docs`.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/labeler.mdx
> +We are using [actions/labeler@v4](https://github.com/actions/labeler) from Github to identify the labels for the pull request. The labeler is a simple tool that allows you to label a pull request wit
> We are using [actions/labeler@v4](https://github.com/actions/labeler) from GitHub to identify and apply labels for the pull request. It is a simple tool that allows us to label a pull request based on the files it contains. For example, pull requests containing files in the `apps/docs` directory will be labelled as `docs`.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/labeler.mdx
> +Defination of the labels is defineted in the [labeler.yml](../../../.github/labeler.yml) file.
> The files relevant to each label are defined in the [labeler.yml](../../../.github/labeler.yml) file.

Is that relative link format going to work as intended once the markdown is deployed? Would it maybe work better to give an absolute URL to GitHub like [https://github.com/TheBuilderDAO/kafe/blob/dev/.github/workflows/labeler.yaml](https://github.com/TheBuilderDAO/kafe/blob/dev/.github/workflows/labeler.yaml) ?

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/labeler.mdx
> +Defination of the labels is defineted in the [labeler.yml](../../../.github/labeler.yml) file.
> The files relevant to each label are defined in the [labeler.yml](../../../.github/labeler.yml) file.

Is that relative link format going to work as intended once the markdown is deployed? Would it maybe work better to give an absolute URL to GitHub like [https://github.com/TheBuilderDAO/kafe/blob/dev/.github/workflows/labeler.yaml](https://github.com/TheBuilderDAO/kafe/blob/dev/.github/workflows/labeler.yaml) ?

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/labeler.mdx
> +
You can remove the extra linebreak here 😄

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/labeler.mdx
> +
You can remove the extra linebreak here 😄

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +Github Action is responsible for checking the Guide Proposal Pull Requests.
> The `proposal-review` Action is responsible for checking the pull requests created from the content proposals on Kafé. It checks the corresponding proposal to determine which reviewers need to be assigned to the pull request.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +Github Action is responsible for checking the Guide Proposal Pull Requests.
> The `proposal-review` Action is responsible for checking the Kafé Guide Proposal pull requests.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  ### get_proposal_slug:
> \### get_proposal_slug

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  ### get_proposal_slug:
> \### get_proposal_slug

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  In this job, we get the slug of the proposal from the PR branch name.
> In this job, we get the slug of the proposal from the pull request branch name.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  The branch name is in the format of `tutorials/<slug>`. By doing Regex we get the slug.
> The branch name is in the format of `tutorials/<slug>`. We match the slug using a regular expression (regex).

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  The branch name is in the format of `tutorials/<slug>`. By doing Regex we get the slug.
> The branch name is in the format of `tutorials/<slug>`. We match the slug using a Regular Expression (regex).

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  ```
Best to leave a linebreak before and after code blocks 🤌 😄

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  ```
Best to leave a linebreak before and after code blocks 🤌 😄

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  ### fetch_proposal:
> \### fetch_proposal

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  ### fetch_proposal:
> \### fetch_proposal

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  And we are assigned as a variable to the context. The following jobs are tu
Looks like this line is incomplete, or got cut off? "The following jobs are tu..."

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  And we are assigned as a variable to the context. The following jobs are tu
Looks like this line is incomplete, or got cut off? "The following jobs are tu..."

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  ```bash
It looks like everything is indented by two, might want to remove the leading whitespace..

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  ```bash
It looks like everything is indented by two, you may want to remove the leading whitespace to prevent rendering problems.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  Output this job is the slug of the proposal.
> The expected output of this job is the slug of the proposal, in lower-kebab-case.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  Output this job is the slug of the proposal.
> The expected output of this job is the slug of the proposal, in lower-kebab-case.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  visual clue for the contributors.
Seems like an extra linebreak here 😅

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  visual clue for the contributors.
Seems like an extra linebreak here 😅

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  If the proposal state is ready to publish, in this step we are setting the `tutorial` and `ready_to_publish` labels to PR to give
>  If the proposal state is `ready_to_publish`, in this step we are adding the `tutorial` and `ready_to_publish` labels to the PR to give a visual cue for the contributors and anybody looking at the list of pull requests.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  If the proposal state is ready to publish, in this step we are setting the `tutorial` and `ready_to_publish` labels to PR to give
>  If the proposal state is `ready_to_publish`, in this step we are adding the `tutorial` and `ready_to_publish` labels to the PR to give a visual cue for the contributors and anybody looking at the list of pull requests.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  As the outcome of the review process the state of the proposal might change to `readyToPublish` or `writing`.
> As the outcome of the review process, the state of the proposal might change to `writing` or `readyToPublish`. In this job, we are updating the Algolia index of the proposal. You can find an explanation of this step in Algolia documentation.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  As the outcome of the review process the state of the proposal might change to `readyToPublish` or `writing`.
> As the outcome of the review process, the state of the proposal might change to `writing` or `readyToPublish`. In this job, we are updating the Algolia index of the proposal. You can find an explanation of this step in the Algolia documentation.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  This is the job where we requesting review from the designated reviewers.
> This is the job where we request reviews of the pull request from the designated reviewers.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  This is the job where we requesting review from the designated reviewers.
> This is the job where we request reviews of the pull request from the designated reviewers.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  We are doing this by utilizing github-script action to use Github Api.
> This leverages the `github-script` action to use the GitHub API to request reviewers.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/proposal-review.mdx
> +  We are doing this by utilizing github-script action to use Github Api.
> This leverages the `github-script` action to use the GitHub API to request reviewers.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +This a Github Action responsible of publishing the guides after they got approval from designated reviewers set by the BuilderDAO admins.
> This GitHub Action is responsible for publishing the guides after they have been approved by the designated reviewers set by the Builder DAO admins.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +This a Github Action responsible of publishing the guides after they got approval from designated reviewers set by the BuilderDAO admins.
> This GitHub Action is responsible for publishing the guides after they have been approved by the designated reviewers set by the Builder DAO admins.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +There's a 2 way to trigger this action. The first is to use the workflow_dispatch trigger. This trigger is used to dispatch the action to the right environment.
> This action has two possible triggers. The first is to use the `workflow_dispatch` trigger. This trigger is used to dispatch the action to the right environment. Only collabrators can trigger this action. The second way is to use the `pull_request_target` trigger. This is used to trigger the action when a pull request is closed, as It's merged to the `dev` or `main` branch.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +There's a 2 way to trigger this action. The first is to use the workflow_dispatch trigger. This trigger is used to dispatch the action to the right environment.
> This action has two possible triggers. The first is to use the `workflow_dispatch` trigger. This trigger is used to dispatch the action to the right environment. Only collabrators can trigger this action. The second way is to use the `pull_request_target` trigger. This is used to trigger the action when a pull request is closed, as It's merged to the `dev` or `main` branch.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +  The branch name is in the format of `tutorials/<slug>`. By doing Regex we get the slug.
> The branch name is in the format of tutorials/<slug>. We match the slug using a regular expression (regex).

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +  The branch name is in the format of `tutorials/<slug>`. By doing Regex we get the slug.
> The branch name is in the format of tutorials/<slug>. We match the slug using a regular expression (regex).

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +  Output this job is the slug of the proposal.
> The expected output of this job is the slug of the proposal, in lower-kebab-case.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +  Output this job is the slug of the proposal.
> The expected output of this job is the slug of the proposal, in lower-kebab-case.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +  In this job, we fetch the proposal from the BuilderDAO CLI tool.
> In this job, we fetch the proposal from the Builder DAO CLI tool.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +  In this job, we fetch the proposal from the BuilderDAO CLI tool.
> In this job, we fetch the proposal from the Builder DAO CLI tool.

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +  And we are assigned as a variable to the context. The following jobs are tu
Same thing as the previous file. It looks like the text has been cut short 😨

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +  And we are assigned as a variable to the context. The following jobs are tu
Same thing as the previous file. It looks like the text has been cut short 😨

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +  There's a few variables that we need to pass to the publish job. the Environment set by the workflow_dispatch trigger is get utilized here. In the case of trigger is `pull_request_target` is merged
> There are a few variables that we need to pass to the publish job. The environment set by the `workflow_dispatch` trigger is utilized here. If the trigger `pull_request_target` is merged to the `main` branch, we use the **Production** environment. If it's merged to the `dev` branch, use the **Preview** environment.

@Necmttn Please let me know if I kept your intent with the edits I'm suggesting 😄

2022-04-27 23:15 UTC, pyr0gan commented on apps/docs/pages/github_workflows/publish.mdx
> +  There's a few variables that we need to pass to the publish job. the Environment set by the workflow_dispatch trigger is get utilized here. In the case of trigger is `pull_request_target` is merged
> There are a few variables that we need to pass to the publish job. The environment set by the `workflow_dispatch` trigger is utilized here. If the trigger `pull_request_target` is merged to the `main` branch, we use the **Production** environment. If it's merged to the `dev` branch, use the **Preview** environment.

@Necmttn Please let me know if I kept your intent with the edits I'm suggesting 😄

2022-04-28 12:19 UTC, Necmttn commented on apps/docs/pages/github_actions/check-required-reviewer.mdx
> +<Authors date="April 27th, 2022">
I have updated authors component.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/5212808/165750386-e1c58ef9-9851-466c-b200-165c99ecb42c.png">
Currently it's automaticly pulls the commit history for the file and render author information like this above.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/5212808/165750500-08b7562c-8204-42fd-8bbd-dfe8dcab4652.png">

2022-04-28 12:20 UTC, Necmttn commented on apps/docs/pages/github_actions/check-required-reviewer.mdx
> +<Authors date="April 27th, 2022">
and usage is like this;
```
<Authors path="apps/docs/pages/github_actions/check-required-reviewer.mdx" />
```

2022-04-28 12:21 UTC, Necmttn commented on apps/docs/pages/github_actions/check-required-reviewer.mdx
> +```
I have set up prettier for lint the MDX files under the docs folder.

2022-04-28 14:10 UTC, pyr0gan commented on apps/docs/pages/github_actions/check-required-reviewer.mdx
> +<Authors date="April 27th, 2022">
Great! Thanks @Necmttn 👍

2022-04-28 14:11 UTC, pyr0gan approved these changes

2022-04-28 17:22 UTC, merged